"use strict";(self.webpackChunktiga=self.webpackChunktiga||[]).push([[474],{74668:function(f,r,n){n.r(r),n.d(r,{demos:function(){return _}});var m=n(17061),e=n.n(m),d=n(17156),l=n.n(d),s=n(67294),v=n(48291),c=n(23023),_={"cnimo-demo-0":{component:s.memo(s.lazy(l()(e()().mark(function a(){var t,u;return e()().wrap(function(o){for(;;)switch(o.prev=o.next){case 0:return o.next=2,Promise.resolve().then(n.bind(n,23023));case 2:return t=o.sent,u=t.Cnimo,o.abrupt("return",{default:function(){return s.createElement(u,{title:"\u4F60xxx"})}});case 5:case"end":return o.stop()}},a)})))),asset:{type:"BLOCK",id:"cnimo-demo-0",refAtomIds:["Cnimo"],dependencies:{"index.jsx":{type:"FILE",value:`import { Cnimo } from 'tiga';

export default () => <Cnimo title="\u4F60xxx" />`},tiga:{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{tiga:c},renderOpts:{compile:function(){var a=l()(e()().mark(function u(){var h,o=arguments;return e()().wrap(function(i){for(;;)switch(i.prev=i.next){case 0:return i.next=2,n.e(335).then(n.bind(n,37335));case 2:return i.abrupt("return",(h=i.sent).default.apply(h,o));case 3:case"end":return i.stop()}},u)}));function t(){return a.apply(this,arguments)}return t}()}}}},23023:function(f,r,n){n.r(r),n.d(r,{Cnimo:function(){return _},Foo:function(){return l},Foos:function(){return v}});var m=n(67294),e=n(85893),d=function(t){return(0,e.jsx)("h4",{children:t.title})},l=d,s=function(t){return(0,e.jsx)("h4",{children:t.title})},v=s,c=function(t){return(0,e.jsx)("button",{onClick:function(){return alert(t.title)},children:"click me "})},_=c},90082:function(f,r,n){n.r(r),n.d(r,{texts:function(){return e}});var m=n(48291);const e=[{value:"This is an example component.",paraId:0,tocIndex:0},{value:"heihieh",paraId:1,tocIndex:0},{value:`import { copy } from '@diezhi/momo'

// \u540C\u6B65\u51FD\u6570 \u53C2\u6570\u9650\u5B9A string \u7C7B\u578B  \u5BF9\u8C61\u7C7B\u578B\u9700\u8981JSON.stringify()
const msg = 'hello world!'
const suc = copy(msg)
console.log(suc) // => true
`,paraId:2}]}}]);
