"use strict";(self.webpackChunktiga=self.webpackChunktiga||[]).push([[474],{74668:function(f,o,n){n.r(o),n.d(o,{demos:function(){return c}});var l=n(15009),e=n.n(l),d=n(99289),m=n.n(d),a=n(67294),v=n(48291),_=n(23023),c={"cnimo-demo-0":{component:a.memo(a.lazy(m()(e()().mark(function r(){var t,u;return e()().wrap(function(s){for(;;)switch(s.prev=s.next){case 0:return s.next=2,Promise.resolve().then(n.bind(n,23023));case 2:return t=s.sent,u=t.Cnimo,s.abrupt("return",{default:function(){return a.createElement(u,{title:"\u4F60xxx"})}});case 5:case"end":return s.stop()}},r)})))),asset:{type:"BLOCK",id:"cnimo-demo-0",refAtomIds:["Cnimo"],dependencies:{"index.jsx":{type:"FILE",value:`import { Cnimo } from 'tiga';

export default () => <Cnimo title="\u4F60xxx" />`},tiga:{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{tiga:_},renderOpts:{compile:function(){var r=m()(e()().mark(function u(){var p,s=arguments;return e()().wrap(function(i){for(;;)switch(i.prev=i.next){case 0:return i.next=2,n.e(335).then(n.bind(n,37335));case 2:return i.abrupt("return",(p=i.sent).default.apply(p,s));case 3:case"end":return i.stop()}},u)}));function t(){return r.apply(this,arguments)}return t}()}}}},23023:function(f,o,n){n.r(o),n.d(o,{Cnimo:function(){return c},Foo:function(){return m},Foos:function(){return v}});var l=n(67294),e=n(85893),d=function(t){return(0,e.jsx)("h4",{children:t.title})},m=d,a=function(t){return(0,e.jsx)("h4",{children:t.title})},v=a,_=function(t){return(0,e.jsx)("button",{onClick:function(){return alert(t.title)},children:"click me "})},c=_},90082:function(f,o,n){n.r(o),n.d(o,{texts:function(){return e}});var l=n(48291);const e=[{value:"This is an example component.",paraId:0,tocIndex:0},{value:"heihieh",paraId:1,tocIndex:0},{value:`import { copy } from '@diezhi/momo'

// \u540C\u6B65\u51FD\u6570 \u53C2\u6570\u9650\u5B9A string \u7C7B\u578B  \u5BF9\u8C61\u7C7B\u578B\u9700\u8981JSON.stringify()
const msg = 'hello world!'
const suc = copy(msg)
console.log(suc) // => true
`,paraId:2}]}}]);
